version: "2"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb-app"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="root" 
      - MONGODB_PASS="root"
      - MONGODB_DATABASE="app"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  postgresql:
    restart: always
    image: sameersbn/postgresql:10
    container_name: "postgresql-app"
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=app
    volumes:
      - ./postgresql:/var/lib/postgresql
  web-php:
    build:
      context: images/web-php
      dockerfile: dockerfile      
    container_name: "web-php"
    ports:
      - "8080:90"
    environment:
      - NGINX_GENERATE_DEFAULT_VHOST=false

